config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :monthlies, :metrics
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  validates :name,     presence: true
  validates :quantity, presence: true
end

app/models/monthly.rb
class Monthly < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric,  only: [:show, :edit, :update, :destroy]
  before_action :set_metrics, only: [:edit, :index]

  def index
  end

  def new
    @metric = Metric.new
  end

  def edit
  end

  def show
    redirect_to edit_metric_path(params[:id])
  end

  def create
    @metric = Metric.new(metric_params)

    if @metric.save
      redirect_to metrics_path, notice: 'Metric was successfully created.'
    else
      render :new
    end
  end

  def update
    if @metric.update(metric_params)
      redirect_to metrics_path, notice: 'Metric was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @metric.destroy
    redirect_to metrics_path, notice: 'Metric was successfully destroyed.'
  end

  private
  def set_metric
    @metric = Metric.find(params[:id])
  end

  def set_metrics
    @metrics = Metric.all
  end

  def metric_params
    params.require(:metric).permit(:name, :quantity)
  end
end

app/controllers/monthlies_controller.rb
class MonthliesController < ApplicationController
  before_action :set_monthly, only: [:show, :edit, :update, :destroy]

  def index
    @monthly_clients   = Monthly.all.where(kind: "client"  ).all.sort_by{ |m| m.year.to_s + m.month.to_s.rjust(2, "0") }
    @monthly_locations = Monthly.all.where(kind: "location").all.sort_by{ |m| m.year.to_s + m.month.to_s.rjust(2, "0") }
  end

  def show
    redirect_to monthlies_path
  end

  def new
    @monthly = Monthly.new
  end

  def edit
  end

  def create
    @monthly = Monthly.new(monthly_params)

    if @monthly.save
      redirect_to monthlies_path, notice: "#{@monthly.year}-#{@monthly.month} was successfully created."
    else
      render :new
    end
  end

  def update
    if @monthly.update(monthly_params)
      redirect_to monthlies_path, notice: "#{@monthly.year}-#{@monthly.month} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @monthly.destroy
    redirect_to monthlies_url, notice: 'Monthly was successfully destroyed.'
  end

  private
    def set_monthly
      @monthly = Monthly.find(params[:id])
    end

    def monthly_params
      params.require(:monthly).permit(:year, :month, :kind, :quantity)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @core_clients                       = Metric.find_by(name: "Core Clients")
    @core_locations                     = Metric.find_by(name: "Core Locations")
    @orion_clients                      = Metric.find_by(name: "Orion Clients")
    @orion_locations                    = Metric.find_by(name: "Orion Locations")
    @new_biz_orion_clients              = Metric.find_by(name: "New Biz Orion Clients")
    @new_biz_orion_locations            = Metric.find_by(name: "New Biz Orion Locations")
    @core_to_orion_client_conversions   = Metric.find_by(name: "Core to Orion Client Conversions")
    @core_to_orion_location_conversions = Metric.find_by(name: "Core to Orion Location Conversions")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/monthlies_helper.rb
module MonthliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orion Progress</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header role="banner">
  <h1>Orion Progress Report</h1>

  <nav role="navigation">
    <ul>
      <li>
        <%= link_to_unless_current("Core vs Orion", root_path) do %>
          <span class="active">Core vs Orion</span>
        <% end %>
      </li>
      <li>
        <%= link_to_unless_current("Monthly Orion Growth", monthlies_path) do %>
          <span class="active">Monthly Orion Growth</span>
        <% end %>
      </li>
    </ul>
  </nav>

</header>

<% unless flash[:notice].blank? %>
  <div class="flash" id="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="flash" id="error">
    <%= flash[:error] %>
  </div>
<% end %>


<%= yield %>

</body>
</html>

app/views/metrics/_form.html.erb
<%= form_for(@metric) do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= link_to "Cancel", metrics_path %>
    <%= f.submit %>
  </div>
<% end %>

app/views/metrics/_metrics.html.erb
<h1>All Metrics</h1>

<table>
  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= link_to metric.name,     edit_metric_path(metric) %></td>
        <td><%= link_to metric.quantity, edit_metric_path(metric) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/metrics/edit.html.erb
<h1>
  <%= link_to "Metrics", metrics_path %> :
  <small><%= @metric.name %></small>
</h1>

<%= render 'form' %>

<hr />

<%= render 'metrics' %>

app/views/metrics/index.html.erb
<%= render 'metrics' %>

app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= render 'form' %>

<%= link_to 'Back', metrics_path %>

app/views/metrics/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @metric.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @metric.quantity %>
</p>

app/views/monthlies/_form.html.erb
<%= form_for(@monthly) do |f| %>
  <% if @monthly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monthly.errors.count, "error") %> prohibited this monthly from being saved:</h2>

      <ul>
      <% @monthly.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monthlies/edit.html.erb
<h1>
  <%= link_to "Monthly", monthlies_path %>
  :
  <small>
    <%= @monthly.kind.pluralize.capitalize %>
    for
    <%= "#{@monthly.year}-#{@monthly.month.to_s.rjust(2, "0")}" %>
  </small>
</h1>

<%= form_for(@monthly) do |f| %>
  <% if @monthly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monthly.errors.count, "error") %> prohibited this monthly from being saved:</h2>

      <ul>
      <% @monthly.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :quantity %><br>
  <%= f.number_field :quantity %>

  <%= f.submit %>
<% end %>

app/views/monthlies/index.html.erb
<%
{
  "Monthly growth of Clients"   => @monthly_clients,
  "Monthly growth of Locations" => @monthly_locations
}.each do |title, data|
%>

<article class="chart chart-bar">
  <h1><%= title %></h1>

  <table>
    <tr>
      <% data.each do |datum| %>
        <td><data style="height: <%= datum.quantity * 5 %>px"><%= datum.quantity %></data></td>
      <% end %>
    </tr>
    <tr>
      <% data.each do |datum| %>
        <th><%= datum.quantity %></th>
      <% end %>
    </tr>
    <tr>
      <% data.each do |datum| %>
        <th>
          <%= link_to edit_monthly_path(datum) do %>
            <%= "#{datum.year}-#{datum.month.to_s.rjust(2, "0")}" %>
          <% end %>
        </th>
      <% end %>
    </tr>
  </table>
</article>

<% end %>

app/views/monthlies/new.html.erb
<h1>New monthly</h1>

<%= render 'form' %>

<%= link_to 'Back', monthlies_path %>

app/views/monthlies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @monthly.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @monthly.month %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @monthly.kind %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @monthly.quantity %>
</p>

<%= link_to 'Edit', edit_monthly_path(@monthly) %> |
<%= link_to 'Back', monthlies_path %>

app/views/welcome/index.html.erb
<article class="chart">
  <h1>New Business</h1>
  <p>Clients and locations new to G5 on Orion only</p>

  <table>
    <tr>
      <th><%= @new_biz_orion_clients.quantity %></th>
      <th><%= @new_biz_orion_locations.quantity %></th>
    </tr>
    <tr>
      <td><data style="height: <%= @new_biz_orion_clients.quantity %>px">  <%= @new_biz_orion_clients.quantity  %></data></td>
      <td><data style="height: <%= @new_biz_orion_locations.quantity %>px"><%= @new_biz_orion_locations.quantity %></data></td>
    </tr>
    <tr>
      <th>Clients</th>
      <th>Locations</th>
    </tr>
  </table>
</article>


<article class="chart">
  <h1>Core to Orion Client Conversions</h1>
  <p>Websites completely migrated off of Core</p>

  <table>
    <tr>
      <th><%= @core_to_orion_client_conversions.quantity %></th>
      <th><%= @core_to_orion_location_conversions.quantity %></th>
    </tr>
    <tr>
      <td><data style="height: <%= @core_to_orion_client_conversions.quantity %>px">  <%= @core_to_orion_client_conversions.quantity  %></data></td>
      <td><data style="height: <%= @core_to_orion_location_conversions.quantity %>px"><%= @core_to_orion_location_conversions.quantity %></data></td>
    </tr>
    <tr>
      <th>Clients</th>
      <th>Locations</th>
    </tr>
  </table>
</article>


<article class="chart chart-comparison">
  <h1>Total Clients</h1>

  <table>
    <tr>
      <th><%= @core_clients.quantity %></th>
      <th><%= @orion_clients.quantity %></th>
    </tr>
    <tr>
      <td><data style="height: <%= @core_clients.quantity %>px"> <%= @core_clients.quantity  %></data></td>
      <td><data style="height: <%= @orion_clients.quantity %>px"><%= @orion_clients.quantity %></data></td>
    </tr>
    <tr>
      <th>Core</th>
      <th>Orion</th>
    </tr>
  </table>
</article>


<article class="chart chart-comparison">
  <h1>Total Locations</h1>

  <table>
    <tr>
      <th><%= @core_locations.quantity %></th>
      <th><%= @orion_locations.quantity %></th>
    </tr>
    <tr>
      <td><data style="height: <%= @core_locations.quantity  %>px"><%= @core_locations.quantity  %></data></td>
      <td><data style="height: <%= @orion_locations.quantity %>px"><%= @orion_locations.quantity %></data></td>
    </tr>
    <tr>
      <th>Core</th>
      <th>Orion</th>
    </tr>
  </table>
</div>